// Generated by purs version 0.15.15
import * as ShowClass from "../ShowClass/index.js";
var showStr = /* #__PURE__ */ ShowClass.myShow(ShowClass.myShowString)("hello");
var showInt = /* #__PURE__ */ ShowClass.myShow(ShowClass.myShowInt)(42);
var showBool = /* #__PURE__ */ ShowClass.myShow(ShowClass.myShowBoolean)(true);
export {
    showInt,
    showStr,
    showBool
};
