// Generated by purs version 0.15.15
var Wrapper = function (x) {
    return x;
};
var Name = function (x) {
    return x;
};
var wrapInt = function (n) {
    return n;
};
var unwrapWrapper = function (v) {
    return v;
};
var unwrapName = function (v) {
    return v;
};
var mkName = function (s) {
    return s;
};
export {
    Name,
    Wrapper,
    mkName,
    unwrapName,
    wrapInt,
    unwrapWrapper
};
