use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    lalrpop::process_root().unwrap();

    // Embed git commit hash at compile time
    let output = std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output();
    if let Ok(output) = output {
        let hash = String::from_utf8_lossy(&output.stdout).trim().to_string();
        println!("cargo:rustc-env=PFC_GIT_COMMIT={hash}");
    }

    generate_passing_fixture_tests();
}

/// Scan `tests/fixtures/original-compiler/passing/` and write one
/// `check_build_unit!(...)` invocation per `.purs` build unit into
/// `$OUT_DIR/passing_fixtures_gen.rs`. The generated file is
/// included by `tests/passing_fixtures.rs`.
///
/// Build units listed in `tests/passing_fixtures_ignore.txt` are
/// emitted as `check_build_unit_ignored!(...)` so they show up as
/// `IGNORED` in `cargo test` output but still run under
/// `cargo test -- --ignored`.
fn generate_passing_fixture_tests() {
    let manifest_dir = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR")
            .expect("CARGO_MANIFEST_DIR set by cargo"),
    );
    let passing_dir = manifest_dir
        .join("tests")
        .join("fixtures")
        .join("original-compiler")
        .join("passing");
    let ignore_file = manifest_dir
        .join("src")
        .join("typecheck_db")
        .join("tests")
        .join("passing_fixtures_ignore.txt");

    println!(
        "cargo:rerun-if-changed={}",
        passing_dir.display(),
    );
    println!(
        "cargo:rerun-if-changed={}",
        ignore_file.display(),
    );

    let entries = match fs::read_dir(&passing_dir) {
        Ok(e) => e,
        Err(_) => {
            // No fixtures dir present — emit an empty file so
            // tests/passing_fixtures.rs still compiles.
            write_generated_file("");
            return;
        }
    };

    // Build the list of build-unit names by stripping `.purs` from
    // every top-level file. We deliberately ignore directories
    // (those are loaded automatically at test time when their
    // same-named primary file runs).
    let mut units: Vec<String> = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_file()
            && path.extension().and_then(|s| s.to_str()) == Some("purs")
        {
            if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                units.push(stem.to_string());
            }
        }
    }
    units.sort();

    let ignore_map = parse_ignore_file(&ignore_file);

    // Validate: every entry in the ignore file must match a real
    // build unit. A leftover ignore entry means a fixture got
    // renamed or deleted and the ignore file is stale.
    let unit_set: std::collections::HashSet<&String> = units.iter().collect();
    let mut stale: Vec<&String> = ignore_map.keys().filter(|k| !unit_set.contains(k)).collect();
    stale.sort();
    if !stale.is_empty() {
        panic!(
            "passing_fixtures_ignore.txt contains entries with no matching fixture: {:?}",
            stale,
        );
    }

    // Emit one macro invocation per build unit.
    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs from\n");
    out.push_str("// `tests/fixtures/original-compiler/passing/` and\n");
    out.push_str("// `tests/passing_fixtures_ignore.txt`. Do not edit.\n\n");
    for unit in &units {
        let test_name = sanitize_ident(unit);
        if let Some(reason) = ignore_map.get(unit) {
            let reason_lit = escape_string_literal(reason);
            out.push_str(&format!(
                "check_build_unit_ignored!({test_name}, \"{unit}\", \"{reason_lit}\");\n",
            ));
        } else {
            out.push_str(&format!(
                "check_build_unit!({test_name}, \"{unit}\");\n",
            ));
        }
    }
    write_generated_file(&out);
}

/// Parse `passing_fixtures_ignore.txt`. Returns a map from fixture
/// name → reason string. Comment lines starting with `# reason:`
/// preceding an entry attach as that entry's reason; bare `#`
/// comments are ignored. Missing reason → `"known gap"`.
fn parse_ignore_file(path: &Path) -> HashMap<String, String> {
    let mut out: HashMap<String, String> = HashMap::new();
    let contents = match fs::read_to_string(path) {
        Ok(s) => s,
        Err(_) => return out,
    };
    let mut pending_reason: Option<String> = None;
    for raw in contents.lines() {
        let line = raw.trim();
        if line.is_empty() {
            pending_reason = None;
            continue;
        }
        if let Some(rest) = line.strip_prefix('#') {
            let r = rest.trim();
            if let Some(reason) = r.strip_prefix("reason:") {
                pending_reason = Some(reason.trim().to_string());
            }
            continue;
        }
        let reason = pending_reason.take().unwrap_or_else(|| "known gap".to_string());
        out.insert(line.to_string(), reason);
    }
    out
}

/// Translate a fixture name (`1110`, `OneConstructor`,
/// `2018`) into a valid Rust test ident: `passes_<sanitized>`,
/// where any non-`[A-Za-z0-9_]` characters become `_`.
fn sanitize_ident(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 7);
    out.push_str("passes_");
    for c in name.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    out
}

/// Escape a string for embedding in a Rust string literal. Only
/// handles `"` and `\` — reasons in our ignore file are short
/// human-written notes, not arbitrary input.
fn escape_string_literal(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn write_generated_file(contents: &str) {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let out_path = PathBuf::from(out_dir).join("passing_fixtures_gen.rs");
    fs::write(&out_path, contents).unwrap_or_else(|e| {
        panic!("failed to write {}: {e}", out_path.display())
    });
}
