// Generated by purs version 0.15.15
var Wrapper = function (x) {
    return x;
};
var Name = function (x) {
    return x;
};
var newtypeWrapper = {
    Coercible0: function () {
        return undefined;
    }
};
var newtypeName = {
    Coercible0: function () {
        return undefined;
    }
};
export {
    Name,
    Wrapper,
    newtypeName,
    newtypeWrapper
};
