// Generated by purs version 0.15.15
var whereWithArgs = function (n) {
    var $$double = function (x) {
        return x;
    };
    return $$double(n);
};
var whereSimple = 42;
var letSimple = 42;
var letMultiple = 1;
export {
    letSimple,
    letMultiple,
    whereSimple,
    whereWithArgs
};
