// Generated by purs version 0.15.15
import * as Types from "../Types/index.js";
var isRed = function (c) {
    if (c instanceof Types.Red) {
        return true;
    };
    return false;
};
var fromMaybe = function (def) {
    return function (m) {
        if (m instanceof Types.Nothing) {
            return def;
        };
        if (m instanceof Types.Just) {
            return m.value0;
        };
        throw new Error("Failed pattern match at UseTypes (line 11, column 19 - line 13, column 14): " + [ m.constructor.name ]);
    };
};
export {
    isRed,
    fromMaybe
};
