// Generated by purs version 0.15.15
var withHelper = function (x) {
    var helper = function (n) {
        return n;
    };
    return helper(x);
};
var useWhere = function (x) {
    return x;
};
var compute = function (x) {
    return function (y) {
        var inner = function (n) {
            return y;
        };
        return inner(x);
    };
};
var applyTwice = function (f) {
    return function (x) {
        return f(f(x));
    };
};
export {
    useWhere,
    applyTwice,
    withHelper,
    compute
};
