// Generated by purs version 0.15.15
var myConvert = function (dict) {
    return dict.myConvert;
};
var doConvert = function (dictMyConvert) {
    var myConvert1 = myConvert(dictMyConvert);
    return function (x) {
        return myConvert1(x);
    };
};
var convertIntString = {
    myConvert: function (v) {
        return "int";
    }
};
export {
    myConvert,
    doConvert,
    convertIntString
};
