// Generated by purs version 0.15.15
var let$prime = 2;
var import$prime = 3;
var default$prime = 4;
var class$prime = 1;
export {
    class$prime,
    let$prime,
    import$prime,
    default$prime
};
