// Generated by purs version 0.15.15
var Nothing = /* #__PURE__ */ (function () {
    function Nothing() {

    };
    Nothing.value = new Nothing();
    return Nothing;
})();
var Just = /* #__PURE__ */ (function () {
    function Just(value0) {
        this.value0 = value0;
    };
    Just.create = function (value0) {
        return new Just(value0);
    };
    return Just;
})();
var Red = /* #__PURE__ */ (function () {
    function Red() {

    };
    Red.value = new Red();
    return Red;
})();
var Green = /* #__PURE__ */ (function () {
    function Green() {

    };
    Green.value = new Green();
    return Green;
})();
var Blue = /* #__PURE__ */ (function () {
    function Blue() {

    };
    Blue.value = new Blue();
    return Blue;
})();
export {
    Red,
    Green,
    Blue,
    Nothing,
    Just
};
