// Generated by purs version 0.15.15
var myShowString = {
    myShow: function (s) {
        return s;
    }
};
var myShowInt = {
    myShow: function (v) {
        return "int";
    }
};
var myShow = function (dict) {
    return dict.myShow;
};
var showValue = function (dictMyShow) {
    var myShow1 = myShow(dictMyShow);
    return function (x) {
        return myShow1(x);
    };
};
export {
    myShow,
    showValue,
    myShowInt,
    myShowString
};
