use std::collections::{HashMap, HashSet};

use crate::cst::Associativity;
use crate::interner::Symbol;
use crate::names::{
    ClassName, ConstructorName, LabelName, OpName, Qualified, TypeName, TypeOpName, TypeVarName,
    ValueName,
};
use crate::typechecker::types::{Role, Scheme, Type};

/// Resolved dictionary expression for codegen.
#[derive(Debug, Clone)]
pub enum DictExpr {
    /// A simple instance with no constraints: e.g., `showInt`, `semiringInt`
    /// Optional module parts hint for disambiguation when instance names collide.
    Var(Symbol, Option<Vec<Symbol>>),
    /// An instance applied to sub-dictionaries: e.g., `showArray(showInt)`
    /// Optional module parts hint for disambiguation when instance names collide.
    App(Symbol, Vec<DictExpr>, Option<Vec<Symbol>>),
    /// Reference to the i-th constraint parameter of the enclosing function/instance.
    /// Used when a deferred constraint resolves to a constraint parameter (not a concrete instance).
    ConstraintArg(usize),
    /// Inline IsSymbol dictionary for a type-level symbol literal.
    /// Generated by the compiler for `IsSymbol "label"` constraints on records.
    /// Produces `{ reflectSymbol: function() { return "label"; } }` in JS.
    InlineIsSymbol(String),
    /// Inline Reflectable dictionary for a type-level literal.
    /// Produces `{ reflectType: function(v) { return <value>; } }` in JS.
    InlineReflectable(ReflectableValue),
    /// Zero-cost constraint (e.g. Coercible) — no runtime dict needed.
    /// Codegen strips the wrapper with an empty `()` call.
    ZeroCost,
}

/// The runtime value for an inline Reflectable dictionary.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ReflectableValue {
    /// Type-level string literal → runtime String
    String(String),
    /// Type-level int literal → runtime Int
    Int(i64),
    /// Type-level True/False → runtime Boolean
    Boolean(bool),
    /// Type-level LT/EQ/GT → runtime Ordering constructor
    Ordering(String),
}

/// Exported information from a type-checked module, available for import by other modules.
#[derive(Debug, Clone, Default)]
pub struct ModuleExports {
    /// Value/constructor/method schemes
    pub values: HashMap<Qualified<ValueName>, Scheme>,
    /// Class method info: method_name → (class_name, class_type_vars)
    pub class_methods: HashMap<Qualified<ValueName>, (Qualified<ClassName>, Vec<TypeVarName>)>,
    /// Data type → constructor names
    pub data_constructors: HashMap<Qualified<TypeName>, Vec<Qualified<ConstructorName>>>,
    /// Constructor details: ctor_name → (parent_type, type_vars, field_types)
    pub ctor_details:
        HashMap<Qualified<ConstructorName>, (Qualified<TypeName>, Vec<TypeVarName>, Vec<Type>)>,
    /// Class instances: class_name → [(types, constraints, instance_name)]
    pub instances: HashMap<
        Qualified<ClassName>,
        Vec<(
            Vec<Type>,
            Vec<(Qualified<ClassName>, Vec<Type>)>,
            Option<Symbol>,
        )>,
    >,
    /// Type-level operators: op → target type name
    pub type_operators: HashMap<Qualified<TypeOpName>, Qualified<TypeName>>,
    /// Value-level operator fixities: operator → (associativity, precedence)
    pub value_fixities: HashMap<Qualified<OpName>, (Associativity, u8)>,
    /// Type-level operator fixities: operator → (associativity, precedence)
    pub type_fixities: HashMap<Qualified<TypeOpName>, (Associativity, u8)>,
    /// Value-level operators that alias functions (not constructors)
    pub function_op_aliases: HashSet<Qualified<OpName>>,
    /// Value-level operator targets: operator → target name (e.g. + → add, : → Cons)
    pub value_operator_targets: HashMap<Qualified<OpName>, Qualified<ValueName>>,
    /// Class methods whose declared type has extra constraints (e.g. `Applicative m =>`).
    /// Used for CycleInDeclaration detection across module boundaries.
    pub constrained_class_methods: HashSet<Qualified<ValueName>>,
    /// Type aliases: alias_name → (params, body_type)
    pub type_aliases: HashMap<Qualified<TypeName>, (Vec<TypeVarName>, Type)>,
    /// Class definitions: class_name → param_count (for arity checking and orphan detection)
    pub class_param_counts: HashMap<Qualified<ClassName>, usize>,
    /// Origin tracking: name → original defining module symbol.
    /// Used to distinguish re-exports of the same definition from
    /// independently defined names that happen to have the same type.
    pub value_origins: HashMap<ValueName, Symbol>,
    pub type_origins: HashMap<TypeName, Symbol>,
    pub class_origins: HashMap<ClassName, Symbol>,
    /// Operator → class method target (e.g. `<>` → `append`).
    /// Used for tracking deferred constraints on operator usage.
    pub operator_class_targets: HashMap<OpName, ValueName>,
    /// Class functional dependencies: class_name → (type_vars, fundeps as index pairs).
    /// Used for fundep-aware orphan instance checking.
    pub class_fundeps: HashMap<ClassName, (Vec<TypeVarName>, Vec<(Vec<usize>, Vec<usize>)>)>,
    /// Type constructor arities: type_name → number of type parameters.
    /// Used to detect over-applied types after type alias expansion.
    pub type_con_arities: HashMap<Qualified<TypeName>, usize>,
    /// Roles for each type constructor: type_name → [Role per type parameter].
    pub type_roles: HashMap<TypeName, Vec<Role>>,
    /// Set of type names declared as newtypes (for Coercible solving).
    pub newtype_names: HashSet<TypeName>,
    /// Signature constraints for exported functions: name → [(class_name, type_args)].
    pub signature_constraints:
        HashMap<Qualified<ValueName>, Vec<(Qualified<ClassName>, Vec<Type>)>>,
    /// Type constructor kinds: type_name → kind Type.
    /// Used for cross-module kind checking (e.g., detecting kind mismatches
    /// between types with the same unqualified name from different modules).
    pub type_kinds: HashMap<TypeName, Type>,
    /// Class kinds: class_name → kind (e.g., Type -> Constraint).
    /// Separate from type_kinds so class kinds don't interfere with type checking
    /// when a class and data type share the same name.
    pub class_type_kinds: HashMap<ClassName, Type>,
    /// Functions whose type has Partial in a function parameter position,
    /// e.g. `unsafePartial :: (Partial => a) -> a`. These discharge Partial
    /// when applied to a partial expression.
    pub partial_dischargers: HashSet<ValueName>,
    /// Pre-computed self-referential type aliases from this module.
    /// Imported at import time to avoid recomputing from scratch.
    pub self_referential_aliases: HashSet<TypeName>,
    /// Class superclass constraints: class_name → (type_var_names, [(superclass_class, superclass_args)])
    /// Used to transitively expand "given" constraints from type signatures.
    pub class_superclasses:
        HashMap<Qualified<ClassName>, (Vec<TypeVarName>, Vec<(Qualified<ClassName>, Vec<Type>)>)>,
    /// Method-level constraint class names from class definitions.
    /// Maps method name → constraint class names. Used for current_given_expanded in instance methods.
    pub method_own_constraints: HashMap<Qualified<ValueName>, Vec<ClassName>>,
    /// Method-level constraint details (with type args) from class definitions.
    /// Maps method name → [(constraint_class, type_args)]. Used for codegen_deferred_constraints
    /// when imported class methods have method-own constraints (e.g., foldMap's Monoid m).
    pub method_own_constraint_details:
        HashMap<ValueName, Vec<(Qualified<ClassName>, Vec<Type>)>>,
    /// Module-level doc-comments (appear before the `module` keyword)
    pub module_doc: Vec<String>,
    /// Instance registry: (class_name, head_type_con) → instance_name
    /// Used for codegen dictionary resolution.
    pub instance_registry: HashMap<(ClassName, TypeName), Symbol>,
    /// Instance name → defining module parts
    pub instance_modules: HashMap<Symbol, Vec<Symbol>>,
    /// Resolved dictionaries for codegen: expression_span → [(class_name, dict_expr)]
    pub resolved_dicts: HashMap<crate::span::Span, Vec<(Symbol, DictExpr)>>,
    /// Constraints for let/where-bound polymorphic functions, keyed by binding span.
    /// Used by codegen to wrap let-bound functions with dict params.
    pub let_binding_constraints:
        HashMap<crate::span::Span, Vec<(Qualified<ClassName>, Vec<Type>)>>,
    /// Record update field info: span of RecordUpdate → all field names in the record type.
    /// Used by codegen to generate object literal copies instead of for-in loops.
    pub record_update_fields: HashMap<crate::span::Span, Vec<LabelName>>,
    /// Class method declaration order: class_name → [method_name, ...] in declaration order.
    /// Used by codegen to order instance dict fields.
    pub class_method_order: HashMap<ClassName, Vec<ValueName>>,
    /// Names with top-level `Partial =>` constraint (wrapped with dictPartial in codegen).
    /// Used by codegen to strip the wrapper inside unsafePartial expressions.
    pub partial_value_names: HashSet<ValueName>,
    /// Return-type inner-forall constraints: function name → [(class_name, type_args)].
    /// For functions whose return type has `forall m. Monad m => ...`, stores the constraints
    /// with type variables from the inner forall. Used by codegen to wrap return values
    /// and apply dicts at call sites.
    pub return_type_constraints:
        HashMap<Qualified<ValueName>, Vec<(Qualified<ClassName>, Vec<Type>)>>,
    /// Number of function arrows before the inner forall in return-type-constrained functions.
    /// For `sequence :: forall t. Sequence t -> (forall m a. Monad m => ...)`, this is 1.
    /// Used by codegen to know after how many args to insert the dict application.
    pub return_type_arrow_depth: HashMap<Qualified<ValueName>, usize>,
    /// Kind annotations for instance type variables.
    /// instance_name → { type_var → kind_name (e.g. "Type", "Symbol") }
    /// Used for polykinded instance dispatch where two instances differ only in kind annotations.
    pub instance_var_kinds: HashMap<Symbol, HashMap<TypeVarName, Symbol>>,
    /// Resolved constructor origins: constructor expression span → defining module parts.
    /// Used by codegen to disambiguate same-named constructors from different types
    /// (e.g., ExitCodes.Success vs Options.Applicative.Types.Success).
    pub resolved_constructors: HashMap<crate::span::Span, Vec<Symbol>>,
}

/// Registry of compiled modules, used to resolve imports.
///
/// Supports layering: a child registry can be created with `with_base()`,
/// which shares an immutable base via `Arc` (zero-copy) and stores new
/// modules in a local overlay. Lookups check the overlay first, then the base.
#[derive(Debug, Clone, Default)]
pub struct ModuleRegistry {
    modules: HashMap<Vec<Symbol>, ModuleExports>,
    base: Option<std::sync::Arc<ModuleRegistry>>,
}

impl ModuleRegistry {
    pub fn new() -> Self {
        Self::default()
    }

    /// Create a child registry layered on top of a shared base.
    /// New modules are stored locally; lookups fall through to the base.
    pub fn with_base(base: std::sync::Arc<ModuleRegistry>) -> Self {
        Self {
            modules: HashMap::new(),
            base: Some(base),
        }
    }

    pub fn register(&mut self, name: &[Symbol], exports: ModuleExports) {
        self.modules.insert(name.to_vec(), exports);
    }

    pub fn lookup(&self, name: &[Symbol]) -> Option<&ModuleExports> {
        self.modules
            .get(name)
            .or_else(|| self.base.as_ref().and_then(|b| b.lookup(name)))
    }

    pub fn contains(&self, name: &[Symbol]) -> bool {
        self.modules.contains_key(name) || self.base.as_ref().map_or(false, |b| b.contains(name))
    }

    /// Iterate over all module names and their exports (overlay + base).
    pub fn iter_all(&self) -> Vec<(&[Symbol], &ModuleExports)> {
        let mut result: HashMap<&[Symbol], &ModuleExports> = HashMap::new();
        // Base modules first (will be overridden by overlay)
        if let Some(base) = &self.base {
            for (name, exports) in base.iter_all() {
                result.insert(name, exports);
            }
        }
        // Overlay modules override base
        for (name, exports) in &self.modules {
            result.insert(name.as_slice(), exports);
        }
        result.into_iter().collect()
    }

    /// Pre-compute registry-derived data for codegen dict resolution.
    /// Call once before parallel module processing to avoid redundant per-module computation.
    pub fn precompute_codegen_dict_cache(&self) -> CodegenDictCache {
        let mut base_registry: HashMap<(Symbol, Symbol), Vec<(Symbol, Option<Vec<Symbol>>)>> = HashMap::new();
        for (mod_parts, mod_exports) in self.iter_all() {
            for (&(class, head), &inst_name) in &mod_exports.instance_registry {
                let defining_mod = mod_exports.instance_modules.get(&inst_name)
                    .cloned()
                    .unwrap_or_else(|| mod_parts.to_vec());
                let entries = base_registry.entry((class.symbol(), head.symbol()))
                    .or_default();
                let entry = (inst_name, Some(defining_mod));
                if !entries.iter().any(|(n, m)| *n == entry.0 && *m == entry.1) {
                    entries.push(entry);
                }
            }
        }

        let mut inst_name_all_modules: HashMap<(String, usize), Vec<Vec<Symbol>>> = HashMap::new();
        for (_, mod_exports) in self.iter_all() {
            for (_class_qi, inst_list) in &mod_exports.instances {
                for (_inst_types, inst_constraints, inst_name_opt) in inst_list {
                    if let Some(inst_name) = inst_name_opt {
                        let name_str = crate::interner::resolve(*inst_name).unwrap_or_default().to_string();
                        let num_constraints = inst_constraints.len();
                        let defining_mod = mod_exports.instance_modules.get(inst_name)
                            .cloned()
                            .unwrap_or_default();
                        if !defining_mod.is_empty() {
                            let all_mods = inst_name_all_modules.entry((name_str, num_constraints)).or_default();
                            if !all_mods.iter().any(|m| m == &defining_mod) {
                                all_mods.push(defining_mod);
                            }
                        }
                    }
                }
            }
        }

        let mut base_instance_var_kinds: HashMap<Symbol, HashMap<TypeVarName, Symbol>> = HashMap::new();
        for (_, mod_exports) in self.iter_all() {
            for (inst_name, kinds) in &mod_exports.instance_var_kinds {
                base_instance_var_kinds.entry(*inst_name).or_insert_with(|| kinds.clone());
            }
        }

        CodegenDictCache {
            base_registry,
            inst_name_all_modules,
            base_instance_var_kinds,
        }
    }
}

/// Pre-computed registry data for codegen dict resolution.
/// Built once via `ModuleRegistry::precompute_codegen_dict_cache()` and shared
/// across parallel module processing to avoid O(N²) per-module registry traversals.
#[derive(Debug, Clone, Default)]
pub struct CodegenDictCache {
    pub base_registry: HashMap<(Symbol, Symbol), Vec<(Symbol, Option<Vec<Symbol>>)>>,
    pub inst_name_all_modules: HashMap<(String, usize), Vec<Vec<Symbol>>>,
    pub base_instance_var_kinds: HashMap<Symbol, HashMap<TypeVarName, Symbol>>,
}
