// Generated by purs version 0.15.15
var myShowString = {
    myShow: function (s) {
        return s;
    }
};
var myShowInt = {
    myShow: function (v) {
        return "int";
    }
};
var myShowBoolean = {
    myShow: function (b) {
        if (b) {
            return "true";
        };
        if (!b) {
            return "false";
        };
        throw new Error("Failed pattern match at ShowClass (line 13, column 14 - line 15, column 21): " + [ b.constructor.name ]);
    }
};
var myShow = function (dict) {
    return dict.myShow;
};
export {
    myShow,
    myShowInt,
    myShowString,
    myShowBoolean
};
