check_failing_build_unit!(f_1071, "1071");
check_failing_build_unit!(f_1169, "1169");
check_failing_build_unit_ignored!(f_1175, "1175", "expected: TypesDoNotUnify");
check_failing_build_unit!(f_1310, "1310");
check_failing_build_unit_ignored!(f_1570, "1570", "expected: ExpectedType");
check_failing_build_unit!(f_1733, "1733");
check_failing_build_unit!(f_1825, "1825");
check_failing_build_unit!(f_1881, "1881");
check_failing_build_unit!(f_2109_bind, "2109-bind");
check_failing_build_unit!(f_2109_discard, "2109-discard");
check_failing_build_unit!(f_2109_negate, "2109-negate");
check_failing_build_unit!(f_2128_class, "2128-class");
check_failing_build_unit!(f_2128_instance, "2128-instance");
check_failing_build_unit_ignored!(f_2197_shouldFail, "2197-shouldFail", "expected: ScopeConflict");
check_failing_build_unit_ignored!(f_2197_shouldFail2, "2197-shouldFail2", "expected: UnknownName");
check_failing_build_unit!(f_2378, "2378");
check_failing_build_unit!(f_2379, "2379");
check_failing_build_unit!(f_2434, "2434");
check_failing_build_unit_ignored!(f_2534, "2534", "expected: InfiniteType");
check_failing_build_unit_ignored!(f_2542, "2542", "expected: UndefinedTypeVariable");
check_failing_build_unit!(f_2567, "2567");
check_failing_build_unit!(f_2601, "2601");
check_failing_build_unit!(f_2616, "2616");
check_failing_build_unit_ignored!(f_2806, "2806", "expected: NoInstanceFound");
check_failing_build_unit!(f_2874_forall, "2874-forall");
check_failing_build_unit!(f_2874_forall2, "2874-forall2");
check_failing_build_unit!(f_2874_wildcard, "2874-wildcard");
check_failing_build_unit!(f_2947, "2947");
check_failing_build_unit_ignored!(f_3077, "3077", "expected: KindsDoNotUnify");
check_failing_build_unit!(f_3132, "3132");
check_failing_build_unit_ignored!(f_3275_BindingGroupErrorPos, "3275-BindingGroupErrorPos", "expected: KindsDoNotUnify");
check_failing_build_unit!(f_3275_DataBindingGroupErrorPos, "3275-DataBindingGroupErrorPos");
check_failing_build_unit!(f_3329, "3329");
check_failing_build_unit_ignored!(f_3335_TypeOpAssociativityError, "3335-TypeOpAssociativityError", "expected: NonAssociativeError");
check_failing_build_unit!(f_3405, "3405");
check_failing_build_unit!(f_3453, "3453");
check_failing_build_unit!(f_3510, "3510");
check_failing_build_unit_ignored!(f_3531_2, "3531-2", "expected: NoInstanceFound");
check_failing_build_unit_ignored!(f_3531_3, "3531-3", "expected: NoInstanceFound");
check_failing_build_unit!(f_3531_4, "3531-4");
check_failing_build_unit!(f_3531_5, "3531-5");
check_failing_build_unit!(f_3531_6, "3531-6");
check_failing_build_unit!(f_3531, "3531");
check_failing_build_unit_ignored!(f_3549_a, "3549-a", "expected: UnknownName");
check_failing_build_unit_ignored!(f_3549, "3549", "expected: KindsDoNotUnify");
check_failing_build_unit_ignored!(f_365, "365", "expected: CycleInDeclaration");
check_failing_build_unit!(f_3689, "3689");
check_failing_build_unit_ignored!(f_3701, "3701", "expected: TypesDoNotUnify");
check_failing_build_unit_skipped!(f_3765_kinds, "3765-kinds", "stack overflow in typecheck_db");
check_failing_build_unit_skipped!(f_3765, "3765", "stack overflow in typecheck_db");
check_failing_build_unit!(f_3891, "3891");
check_failing_build_unit_ignored!(f_4019_1, "4019-1", "expected: KindsDoNotUnify");
check_failing_build_unit_ignored!(f_4019_2, "4019-2", "expected: KindsDoNotUnify");
check_failing_build_unit!(f_4024_2, "4024-2");
check_failing_build_unit!(f_4024, "4024");
check_failing_build_unit!(f_4028, "4028");
check_failing_build_unit_ignored!(f_4158, "4158", "expected: TypesDoNotUnify");
check_failing_build_unit!(f_438, "438");
check_failing_build_unit_ignored!(f_4382, "4382", "expected: UnknownName");
check_failing_build_unit!(f_4408Acyclic, "4408Acyclic");
check_failing_build_unit!(f_4408AcyclicRecursive, "4408AcyclicRecursive");
check_failing_build_unit!(f_4408Cyclic, "4408Cyclic");
check_failing_build_unit!(f_4408CyclicTail, "4408CyclicTail");
check_failing_build_unit!(f_4408CyclicTriple, "4408CyclicTriple");
check_failing_build_unit!(f_4466, "4466");
check_failing_build_unit!(f_4483, "4483");
check_failing_build_unit!(f_4522, "4522");
check_failing_build_unit!(f_881, "881");
check_failing_build_unit!(f_AnonArgument1, "AnonArgument1");
check_failing_build_unit!(f_AnonArgument2, "AnonArgument2");
check_failing_build_unit!(f_AnonArgument3, "AnonArgument3");
check_failing_build_unit_ignored!(f_ApostropheModuleName, "ApostropheModuleName", "expected: ErrorParsingModule");
check_failing_build_unit_ignored!(f_ArgLengthMismatch, "ArgLengthMismatch", "expected: ArgListLengthsDiffer");
check_failing_build_unit!(f_ArrayType, "ArrayType");
check_failing_build_unit!(f_Arrays, "Arrays");
check_failing_build_unit_ignored!(f_AtPatternPrecedence, "AtPatternPrecedence", "expected: ArgListLengthsDiffer");
check_failing_build_unit_ignored!(f_BifunctorInstance1, "BifunctorInstance1", "expected: CannotDeriveInvalidConstructorArg");
check_failing_build_unit!(f_BindInDo_2, "BindInDo-2");
check_failing_build_unit!(f_BindInDo, "BindInDo");
check_failing_build_unit!(f_CannotDeriveNewtypeForData, "CannotDeriveNewtypeForData");
check_failing_build_unit!(f_CaseBinderLengthsDiffer, "CaseBinderLengthsDiffer");
check_failing_build_unit!(f_CaseDoesNotMatchAllConstructorArgs, "CaseDoesNotMatchAllConstructorArgs");
check_failing_build_unit!(f_ClassHeadNoVTA1, "ClassHeadNoVTA1");
check_failing_build_unit!(f_ClassHeadNoVTA2, "ClassHeadNoVTA2");
check_failing_build_unit!(f_ClassHeadNoVTA3, "ClassHeadNoVTA3");
check_failing_build_unit!(f_ClassHeadNoVTA4, "ClassHeadNoVTA4");
check_failing_build_unit!(f_ClassHeadNoVTA5, "ClassHeadNoVTA5");
check_failing_build_unit!(f_ClassHeadNoVTA6a, "ClassHeadNoVTA6a");
check_failing_build_unit!(f_ClassHeadNoVTA6b, "ClassHeadNoVTA6b");
check_failing_build_unit!(f_ClassHeadNoVTA6c, "ClassHeadNoVTA6c");
check_failing_build_unit!(f_ClassHeadNoVTA7, "ClassHeadNoVTA7");
check_failing_build_unit_ignored!(f_CoercibleClosedRowsDoNotUnify, "CoercibleClosedRowsDoNotUnify", "expected: TypesDoNotUnify");
check_failing_build_unit!(f_CoercibleConstrained1, "CoercibleConstrained1");
check_failing_build_unit_ignored!(f_CoercibleConstrained2, "CoercibleConstrained2", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_CoercibleConstrained3, "CoercibleConstrained3", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_CoercibleForeign, "CoercibleForeign", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_CoercibleForeign2, "CoercibleForeign2", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_CoercibleForeign3, "CoercibleForeign3", "expected: TypesDoNotUnify");
check_failing_build_unit!(f_CoercibleHigherKindedData, "CoercibleHigherKindedData");
check_failing_build_unit!(f_CoercibleHigherKindedNewtypes, "CoercibleHigherKindedNewtypes");
check_failing_build_unit_ignored!(f_CoercibleKindMismatch, "CoercibleKindMismatch", "expected: KindsDoNotUnify");
check_failing_build_unit_ignored!(f_CoercibleNominal, "CoercibleNominal", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_CoercibleNominalTypeApp, "CoercibleNominalTypeApp", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_CoercibleNominalWrapped, "CoercibleNominalWrapped", "expected: TypesDoNotUnify");
check_failing_build_unit!(f_CoercibleNonCanonical1, "CoercibleNonCanonical1");
check_failing_build_unit!(f_CoercibleNonCanonical2, "CoercibleNonCanonical2");
check_failing_build_unit!(f_CoercibleOpenRowsDoNotUnify, "CoercibleOpenRowsDoNotUnify");
check_failing_build_unit!(f_CoercibleRepresentational, "CoercibleRepresentational");
check_failing_build_unit!(f_CoercibleRepresentational2, "CoercibleRepresentational2");
check_failing_build_unit!(f_CoercibleRepresentational3, "CoercibleRepresentational3");
check_failing_build_unit!(f_CoercibleRepresentational4, "CoercibleRepresentational4");
check_failing_build_unit!(f_CoercibleRepresentational5, "CoercibleRepresentational5");
check_failing_build_unit!(f_CoercibleRepresentational6, "CoercibleRepresentational6");
check_failing_build_unit!(f_CoercibleRepresentational7, "CoercibleRepresentational7");
check_failing_build_unit!(f_CoercibleRepresentational8, "CoercibleRepresentational8");
check_failing_build_unit!(f_CoercibleRoleMismatch1, "CoercibleRoleMismatch1");
check_failing_build_unit!(f_CoercibleRoleMismatch2, "CoercibleRoleMismatch2");
check_failing_build_unit!(f_CoercibleRoleMismatch3, "CoercibleRoleMismatch3");
check_failing_build_unit!(f_CoercibleRoleMismatch4, "CoercibleRoleMismatch4");
check_failing_build_unit!(f_CoercibleRoleMismatch5, "CoercibleRoleMismatch5");
check_failing_build_unit!(f_CoercibleUnknownRowTail1, "CoercibleUnknownRowTail1");
check_failing_build_unit!(f_CoercibleUnknownRowTail2, "CoercibleUnknownRowTail2");
check_failing_build_unit_ignored!(f_CompareInt1, "CompareInt1", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_CompareInt10, "CompareInt10", "expected: TypesDoNotUnify");
check_failing_build_unit!(f_CompareInt11, "CompareInt11");
check_failing_build_unit!(f_CompareInt12, "CompareInt12");
check_failing_build_unit_ignored!(f_CompareInt2, "CompareInt2", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_CompareInt3, "CompareInt3", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_CompareInt4, "CompareInt4", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_CompareInt5, "CompareInt5", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_CompareInt6, "CompareInt6", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_CompareInt7, "CompareInt7", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_CompareInt8, "CompareInt8", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_CompareInt9, "CompareInt9", "expected: TypesDoNotUnify");
check_failing_build_unit!(f_ConflictingExports, "ConflictingExports");
check_failing_build_unit_ignored!(f_ConflictingImports, "ConflictingImports", "expected: ScopeConflict");
check_failing_build_unit!(f_ConflictingImports2, "ConflictingImports2");
check_failing_build_unit!(f_ConflictingQualifiedImports, "ConflictingQualifiedImports");
check_failing_build_unit!(f_ConflictingQualifiedImports2, "ConflictingQualifiedImports2");
check_failing_build_unit!(f_ConstraintFailure, "ConstraintFailure");
check_failing_build_unit!(f_ConstraintInForeignImport, "ConstraintInForeignImport");
check_failing_build_unit_ignored!(f_ConstraintInference, "ConstraintInference", "expected: AmbiguousTypeVariables");
check_failing_build_unit_ignored!(f_ContravariantInstance1, "ContravariantInstance1", "expected: CannotDeriveInvalidConstructorArg");
check_failing_build_unit!(f_CtorArityTooFew, "CtorArityTooFew");
check_failing_build_unit!(f_CycleInForeignDataKinds, "CycleInForeignDataKinds");
check_failing_build_unit!(f_CycleInKindDeclaration, "CycleInKindDeclaration");
check_failing_build_unit!(f_DctorOperatorAliasExport, "DctorOperatorAliasExport");
check_failing_build_unit!(f_DeclConflictClassCtor, "DeclConflictClassCtor");
check_failing_build_unit!(f_DeclConflictClassSynonym, "DeclConflictClassSynonym");
check_failing_build_unit!(f_DeclConflictClassType, "DeclConflictClassType");
check_failing_build_unit!(f_DeclConflictCtorClass, "DeclConflictCtorClass");
check_failing_build_unit!(f_DeclConflictCtorCtor, "DeclConflictCtorCtor");
check_failing_build_unit!(f_DeclConflictDuplicateCtor, "DeclConflictDuplicateCtor");
check_failing_build_unit!(f_DeclConflictSynonymClass, "DeclConflictSynonymClass");
check_failing_build_unit!(f_DeclConflictSynonymType, "DeclConflictSynonymType");
check_failing_build_unit!(f_DeclConflictTypeClass, "DeclConflictTypeClass");
check_failing_build_unit!(f_DeclConflictTypeSynonym, "DeclConflictTypeSynonym");
check_failing_build_unit!(f_DeclConflictTypeType, "DeclConflictTypeType");
check_failing_build_unit_ignored!(f_DeprecatedFFICommonJSModule, "DeprecatedFFICommonJSModule", "expected: DeprecatedFFICommonJSModule");
check_failing_build_unit_ignored!(f_DeprecatedFFIPrime, "DeprecatedFFIPrime", "expected: DeprecatedFFIPrime");
check_failing_build_unit_ignored!(f_DeriveInstanceRecordAlias, "DeriveInstanceRecordAlias", "expected: InvalidInstanceHead");
check_failing_build_unit_ignored!(f_DiffKindsSameName, "DiffKindsSameName", "expected: KindsDoNotUnify");
check_failing_build_unit_ignored!(
    f_Do,
    "Do",
    "panic: parser invariant violated — last statement of a Do block must be Discard, got Let"
);
check_failing_build_unit_ignored!(f_DoNotSuggestComposition, "DoNotSuggestComposition", "expected: TypesDoNotUnify");
check_failing_build_unit!(f_DoNotSuggestComposition2, "DoNotSuggestComposition2");
check_failing_build_unit!(f_DuplicateDeclarationsInLet, "DuplicateDeclarationsInLet");
check_failing_build_unit!(f_DuplicateDeclarationsInLet2, "DuplicateDeclarationsInLet2");
check_failing_build_unit!(f_DuplicateDeclarationsInLet3, "DuplicateDeclarationsInLet3");
check_failing_build_unit_ignored!(f_DuplicateInstance, "DuplicateInstance", "expected: DuplicateInstance");
check_failing_build_unit!(f_DuplicateModule, "DuplicateModule");
check_failing_build_unit!(f_DuplicateProperties, "DuplicateProperties");
check_failing_build_unit!(f_DuplicateRoleDeclaration, "DuplicateRoleDeclaration");
check_failing_build_unit!(f_DuplicateTypeClass, "DuplicateTypeClass");
check_failing_build_unit!(f_DuplicateTypeVars, "DuplicateTypeVars");
check_failing_build_unit!(f_EmptyCase, "EmptyCase");
check_failing_build_unit!(f_EmptyClass, "EmptyClass");
check_failing_build_unit!(f_EmptyDo, "EmptyDo");
check_failing_build_unit_ignored!(f_ExpectedWildcard, "ExpectedWildcard", "expected: ExpectedWildcard");
check_failing_build_unit!(f_ExportConflictClass, "ExportConflictClass");
check_failing_build_unit!(f_ExportConflictClassAndType, "ExportConflictClassAndType");
check_failing_build_unit!(f_ExportConflictCtor, "ExportConflictCtor");
check_failing_build_unit!(f_ExportConflictType, "ExportConflictType");
check_failing_build_unit!(f_ExportConflictTypeOp, "ExportConflictTypeOp");
check_failing_build_unit!(f_ExportConflictValue, "ExportConflictValue");
check_failing_build_unit!(f_ExportConflictValueOp, "ExportConflictValueOp");
check_failing_build_unit_ignored!(f_ExportExplicit, "ExportExplicit", "expected: UnknownExport");
check_failing_build_unit!(f_ExportExplicit1, "ExportExplicit1");
check_failing_build_unit_ignored!(f_ExportExplicit2, "ExportExplicit2", "expected: UnknownExportDataConstructor");
check_failing_build_unit!(f_ExportExplicit3, "ExportExplicit3");
check_failing_build_unit_ignored!(f_ExtraRecordField, "ExtraRecordField", "expected: AdditionalProperty");
check_failing_build_unit!(f_ExtraneousClassMember, "ExtraneousClassMember");
check_failing_build_unit_ignored!(f_FFIDefaultCJSExport, "FFIDefaultCJSExport", "expected: DeprecatedFFICommonJSModule");
check_failing_build_unit_ignored!(f_Foldable, "Foldable", "expected: CycleInDeclaration");
check_failing_build_unit!(f_FoldableInstance1, "FoldableInstance1");
check_failing_build_unit_ignored!(f_FoldableInstance10, "FoldableInstance10", "expected: CannotDeriveInvalidConstructorArg");
check_failing_build_unit_ignored!(f_FoldableInstance2, "FoldableInstance2", "expected: KindsDoNotUnify");
check_failing_build_unit_ignored!(f_FoldableInstance3, "FoldableInstance3", "expected: KindsDoNotUnify");
check_failing_build_unit_ignored!(f_FoldableInstance4, "FoldableInstance4", "expected: CannotDeriveInvalidConstructorArg");
check_failing_build_unit_ignored!(f_FoldableInstance6, "FoldableInstance6", "expected: CannotDeriveInvalidConstructorArg");
check_failing_build_unit_ignored!(f_FoldableInstance8, "FoldableInstance8", "expected: CannotDeriveInvalidConstructorArg");
check_failing_build_unit_ignored!(f_FoldableInstance9, "FoldableInstance9", "expected: CannotDeriveInvalidConstructorArg");
check_failing_build_unit_ignored!(f_FunctorInstance1, "FunctorInstance1", "expected: CannotDeriveInvalidConstructorArg");
check_failing_build_unit!(f_FundepMissingField, "FundepMissingField");
check_failing_build_unit!(f_FundepMissingFieldDeeper, "FundepMissingFieldDeeper");
check_failing_build_unit!(f_FundepMissingFieldMiddleChain, "FundepMissingFieldMiddleChain");
check_failing_build_unit_ignored!(f_Generalization1, "Generalization1", "expected: CannotGeneralizeRecursiveFunction");
check_failing_build_unit_ignored!(f_Generalization2, "Generalization2", "expected: CannotGeneralizeRecursiveFunction");
check_failing_build_unit!(f_HalogenStateIncorrect, "HalogenStateIncorrect");
check_failing_build_unit!(f_HalogenStateIncorrectAnnotation, "HalogenStateIncorrectAnnotation");
check_failing_build_unit!(f_HalogenStateIncorrectAnnotationOnTypeVariable, "HalogenStateIncorrectAnnotationOnTypeVariable");
check_failing_build_unit!(f_HalogenStateIncorrectRecord, "HalogenStateIncorrectRecord");
check_failing_build_unit!(f_HalogenStateIncorrectRecordNested, "HalogenStateIncorrectRecordNested");
check_failing_build_unit!(f_HalogenStateIncorrectRecordOpen, "HalogenStateIncorrectRecordOpen");
check_failing_build_unit!(f_HalogenStateIncorrectRecordUpdate, "HalogenStateIncorrectRecordUpdate");
check_failing_build_unit!(f_ImportExplicit, "ImportExplicit");
check_failing_build_unit!(f_ImportExplicit2, "ImportExplicit2");
check_failing_build_unit!(f_ImportHidingModule, "ImportHidingModule");
check_failing_build_unit!(f_ImportModule, "ImportModule");
check_failing_build_unit_ignored!(f_InfiniteKind, "InfiniteKind", "expected: InfiniteKind");
check_failing_build_unit_ignored!(f_InfiniteKind2, "InfiniteKind2", "expected: InfiniteKind");
check_failing_build_unit!(f_InfiniteType, "InfiniteType");
check_failing_build_unit!(f_InstanceChainBothUnknownAndMatch, "InstanceChainBothUnknownAndMatch");
check_failing_build_unit!(f_InstanceChainSkolemUnknownMatch, "InstanceChainSkolemUnknownMatch");
check_failing_build_unit!(f_InstanceExport, "InstanceExport");
check_failing_build_unit!(f_InstanceNamedWithoutSeparator, "InstanceNamedWithoutSeparator");
check_failing_build_unit_ignored!(f_InstanceSigsBodyIncorrect, "InstanceSigsBodyIncorrect", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_InstanceSigsDifferentTypes, "InstanceSigsDifferentTypes", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_InstanceSigsIncorrectType, "InstanceSigsIncorrectType", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_InstanceSigsOrphanTypeDeclaration, "InstanceSigsOrphanTypeDeclaration", "expected: OrphanTypeDeclaration");
check_failing_build_unit!(f_IntAsRecordLabel, "IntAsRecordLabel");
check_failing_build_unit!(f_IntOutOfRange, "IntOutOfRange");
check_failing_build_unit_ignored!(f_IntToString1, "IntToString1", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_IntToString2, "IntToString2", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_IntToString3, "IntToString3", "expected: TypesDoNotUnify");
check_failing_build_unit!(f_InvalidCoercibleInstanceDeclaration, "InvalidCoercibleInstanceDeclaration");
check_failing_build_unit_ignored!(f_InvalidDerivedInstance, "InvalidDerivedInstance", "expected: ClassInstanceArityMismatch");
check_failing_build_unit!(f_InvalidDerivedInstance2, "InvalidDerivedInstance2");
check_failing_build_unit!(f_InvalidDerivedInstance3, "InvalidDerivedInstance3");
check_failing_build_unit!(f_InvalidOperatorInBinder, "InvalidOperatorInBinder");
check_failing_build_unit_ignored!(f_KindError, "KindError", "expected: KindsDoNotUnify");
check_failing_build_unit_ignored!(f_KindStar, "KindStar", "expected: ExpectedType");
check_failing_build_unit!(f_LacksWithSubGoal, "LacksWithSubGoal");
check_failing_build_unit!(f_LeadingZeros1, "LeadingZeros1");
check_failing_build_unit!(f_LeadingZeros2, "LeadingZeros2");
check_failing_build_unit!(f_Let, "Let");
check_failing_build_unit!(f_LetPatterns1, "LetPatterns1");
check_failing_build_unit!(f_LetPatterns2, "LetPatterns2");
check_failing_build_unit!(f_LetPatterns3, "LetPatterns3");
check_failing_build_unit!(f_LetPatterns4, "LetPatterns4");
check_failing_build_unit!(f_MPTCs, "MPTCs");
check_failing_build_unit!(f_MissingClassExport, "MissingClassExport");
check_failing_build_unit!(f_MissingClassMember, "MissingClassMember");
check_failing_build_unit!(f_MissingClassMemberExport, "MissingClassMemberExport");
check_failing_build_unit_ignored!(f_MissingFFIImplementations, "MissingFFIImplementations", "expected: MissingFFIImplementations");
check_failing_build_unit!(f_MissingRecordField, "MissingRecordField");
check_failing_build_unit_ignored!(f_MixedAssociativityError, "MixedAssociativityError", "expected: MixedAssociativityError");
check_failing_build_unit_ignored!(f_MonoKindDataBindingGroup, "MonoKindDataBindingGroup", "expected: KindsDoNotUnify");
check_failing_build_unit_ignored!(f_MultipleErrors, "MultipleErrors", "expected: TypesDoNotUnify");
check_failing_build_unit!(f_MultipleErrors2, "MultipleErrors2");
check_failing_build_unit!(f_MultipleTypeOpFixities, "MultipleTypeOpFixities");
check_failing_build_unit!(f_MultipleValueOpFixities, "MultipleValueOpFixities");
check_failing_build_unit!(f_MutRec, "MutRec");
check_failing_build_unit!(f_MutRec2, "MutRec2");
check_failing_build_unit_ignored!(f_NestedRecordLabelOnTypeError, "NestedRecordLabelOnTypeError", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_NestedRecordUpdateAliasWrongType, "NestedRecordUpdateAliasWrongType", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_NestedRecordUpdateFlatInModify, "NestedRecordUpdateFlatInModify", "expected: TypesDoNotUnify");
check_failing_build_unit!(f_NestedRecordUpdateFlatMismatch, "NestedRecordUpdateFlatMismatch");
check_failing_build_unit_ignored!(f_NestedRecordUpdateFlatVsNested, "NestedRecordUpdateFlatVsNested", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_NestedRecordUpdatePolyModify, "NestedRecordUpdatePolyModify", "expected: TypesDoNotUnify");
check_failing_build_unit!(f_NestedRecordUpdateTypeMismatch, "NestedRecordUpdateTypeMismatch");
check_failing_build_unit!(f_NestedRecordUpdateWrongValueType, "NestedRecordUpdateWrongValueType");
check_failing_build_unit!(f_NewtypeInstance, "NewtypeInstance");
check_failing_build_unit!(f_NewtypeInstance2, "NewtypeInstance2");
check_failing_build_unit_ignored!(f_NewtypeInstance3, "NewtypeInstance3", "expected: InvalidNewtypeInstance");
check_failing_build_unit!(f_NewtypeInstance4, "NewtypeInstance4");
check_failing_build_unit_ignored!(f_NewtypeInstance5, "NewtypeInstance5", "expected: InvalidNewtypeInstance");
check_failing_build_unit!(f_NewtypeInstance6, "NewtypeInstance6");
check_failing_build_unit!(f_NewtypeMultiArgs, "NewtypeMultiArgs");
check_failing_build_unit!(f_NewtypeMultiCtor, "NewtypeMultiCtor");
check_failing_build_unit!(f_NewtypeUnnamedInstance, "NewtypeUnnamedInstance");
check_failing_build_unit!(f_NoInstanceMixedUnif, "NoInstanceMixedUnif");
check_failing_build_unit_ignored!(f_NonAssociativeError, "NonAssociativeError", "expected: NonAssociativeError");
check_failing_build_unit_ignored!(f_NonExhaustivePatGuard, "NonExhaustivePatGuard", "expected: NoInstanceFound");
check_failing_build_unit!(f_NullaryAbs, "NullaryAbs");
check_failing_build_unit!(f_Object, "Object");
check_failing_build_unit!(f_OperatorAliasNoExport, "OperatorAliasNoExport");
check_failing_build_unit!(f_OperatorAt, "OperatorAt");
check_failing_build_unit!(f_OperatorBackslash, "OperatorBackslash");
check_failing_build_unit!(f_OperatorSections, "OperatorSections");
check_failing_build_unit_ignored!(f_OperatorSections2, "OperatorSections2", "expected: IncorrectAnonymousArgument");
check_failing_build_unit!(f_OrphanInstance, "OrphanInstance");
check_failing_build_unit_ignored!(f_OrphanInstanceFunDepCycle, "OrphanInstanceFunDepCycle", "expected: OrphanInstance");
check_failing_build_unit!(f_OrphanInstanceNullary, "OrphanInstanceNullary");
check_failing_build_unit_ignored!(f_OrphanInstanceWithDetermined, "OrphanInstanceWithDetermined", "expected: OrphanInstance");
check_failing_build_unit!(f_OrphanKindDeclaration1, "OrphanKindDeclaration1");
check_failing_build_unit_ignored!(f_OrphanKindDeclaration2, "OrphanKindDeclaration2", "expected: OrphanKindDeclaration");
check_failing_build_unit!(f_OrphanRoleDeclaration1, "OrphanRoleDeclaration1");
check_failing_build_unit!(f_OrphanRoleDeclaration2, "OrphanRoleDeclaration2");
check_failing_build_unit!(f_OrphanRoleDeclaration3, "OrphanRoleDeclaration3");
check_failing_build_unit!(f_OrphanTypeDecl, "OrphanTypeDecl");
check_failing_build_unit!(f_OrphanUnnamedInstance, "OrphanUnnamedInstance");
check_failing_build_unit_ignored!(f_OverlapAcrossModules, "OverlapAcrossModules", "expected: OverlappingInstances");
check_failing_build_unit_ignored!(f_OverlapAcrossModulesUnnamedInstance, "OverlapAcrossModulesUnnamedInstance", "expected: OverlappingInstances");
check_failing_build_unit!(f_OverlappingArguments, "OverlappingArguments");
check_failing_build_unit!(f_OverlappingBinders, "OverlappingBinders");
check_failing_build_unit_ignored!(f_OverlappingInstances, "OverlappingInstances", "expected: OverlappingInstances");
check_failing_build_unit_ignored!(f_OverlappingUnnamedInstances, "OverlappingUnnamedInstances", "expected: OverlappingInstances");
check_failing_build_unit!(f_OverlappingVars, "OverlappingVars");
check_failing_build_unit!(f_PASTrumpsKDNU1, "PASTrumpsKDNU1");
check_failing_build_unit!(f_PASTrumpsKDNU2, "PASTrumpsKDNU2");
check_failing_build_unit!(f_PASTrumpsKDNU3, "PASTrumpsKDNU3");
check_failing_build_unit!(f_PASTrumpsKDNU4, "PASTrumpsKDNU4");
check_failing_build_unit!(f_PASTrumpsKDNU5, "PASTrumpsKDNU5");
check_failing_build_unit!(f_PASTrumpsKDNU6, "PASTrumpsKDNU6");
check_failing_build_unit!(f_PASTrumpsKDNU7, "PASTrumpsKDNU7");
check_failing_build_unit_ignored!(f_PolykindInstanceOverlapping, "PolykindInstanceOverlapping", "expected: OverlappingInstances");
check_failing_build_unit_ignored!(f_PolykindInstantiatedInstance, "PolykindInstantiatedInstance", "expected: KindsDoNotUnify");
check_failing_build_unit_ignored!(f_PolykindInstantiation, "PolykindInstantiation", "expected: KindsDoNotUnify");
check_failing_build_unit_ignored!(f_PolykindUnnamedInstanceOverlapping, "PolykindUnnamedInstanceOverlapping", "expected: OverlappingInstances");
check_failing_build_unit_ignored!(f_PossiblyInfiniteCoercibleInstance, "PossiblyInfiniteCoercibleInstance", "expected: PossiblyInfiniteCoercibleInstance");
check_failing_build_unit!(f_PrimModuleReserved, "PrimModuleReserved");
check_failing_build_unit_ignored!(f_PrimRow, "PrimRow", "expected: UnknownName");
check_failing_build_unit!(f_PrimSubModuleReserved, "PrimSubModuleReserved");
check_failing_build_unit!(f_ProgrammablePolykindedTypeErrorsTypeString, "ProgrammablePolykindedTypeErrorsTypeString");
check_failing_build_unit!(f_ProgrammableTypeErrors, "ProgrammableTypeErrors");
check_failing_build_unit!(f_ProgrammableTypeErrorsTypeString, "ProgrammableTypeErrorsTypeString");
check_failing_build_unit_ignored!(f_QualifiedAliasShadow, "QualifiedAliasShadow", "expected: UnknownName");
check_failing_build_unit!(f_QualifiedOperators, "QualifiedOperators");
check_failing_build_unit!(f_QualifiedOperators2, "QualifiedOperators2");
check_failing_build_unit_ignored!(f_QuantificationCheckFailure, "QuantificationCheckFailure", "expected: QuantificationCheckFailureInKind");
check_failing_build_unit_ignored!(f_QuantificationCheckFailure2, "QuantificationCheckFailure2", "expected: QuantificationCheckFailureInType");
check_failing_build_unit_ignored!(f_QuantificationCheckFailure3, "QuantificationCheckFailure3", "expected: VisibleQuantificationCheckFailureInType");
check_failing_build_unit_ignored!(f_QuantifiedKind, "QuantifiedKind", "expected: UndefinedTypeVariable");
check_failing_build_unit!(f_Rank2Types, "Rank2Types");
check_failing_build_unit_ignored!(f_RecordLabelOnTypeError, "RecordLabelOnTypeError", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_RecordLabelOnTypeErrorImmediate, "RecordLabelOnTypeErrorImmediate", "expected: TypesDoNotUnify");
check_failing_build_unit_ignored!(f_RequiredHiddenType, "RequiredHiddenType", "expected: TransitiveExportError");
check_failing_build_unit!(f_Reserved, "Reserved");
check_failing_build_unit!(f_RoleDeclarationArityMismatch, "RoleDeclarationArityMismatch");
check_failing_build_unit!(f_RoleDeclarationArityMismatchForeign, "RoleDeclarationArityMismatchForeign");
check_failing_build_unit!(f_RoleDeclarationArityMismatchForeign2, "RoleDeclarationArityMismatchForeign2");
check_failing_build_unit!(f_RoleDeclarationArityMismatchForeign3, "RoleDeclarationArityMismatchForeign3");
check_failing_build_unit!(f_RoleDeclarationArityMismatchForeign4, "RoleDeclarationArityMismatchForeign4");
check_failing_build_unit_ignored!(f_RowConstructors1, "RowConstructors1", "expected: KindsDoNotUnify");
check_failing_build_unit!(f_RowConstructors2, "RowConstructors2");
check_failing_build_unit_ignored!(f_RowConstructors3, "RowConstructors3", "expected: KindsDoNotUnify");
check_failing_build_unit!(f_RowInInstanceNotDetermined0, "RowInInstanceNotDetermined0");
check_failing_build_unit_ignored!(f_RowInInstanceNotDetermined1, "RowInInstanceNotDetermined1", "expected: InvalidInstanceHead");
check_failing_build_unit_ignored!(f_RowInInstanceNotDetermined2, "RowInInstanceNotDetermined2", "expected: InvalidInstanceHead");
check_failing_build_unit!(f_RowLacks, "RowLacks");
check_failing_build_unit_ignored!(f_RowsInKinds, "RowsInKinds", "expected: KindsDoNotUnify");
check_failing_build_unit!(f_ScopedKindVariableSynonym, "ScopedKindVariableSynonym");
check_failing_build_unit!(f_SelfCycleInForeignDataKinds, "SelfCycleInForeignDataKinds");
check_failing_build_unit!(f_SelfCycleInKindDeclaration, "SelfCycleInKindDeclaration");
check_failing_build_unit!(f_SelfCycleInTypeClassDeclaration, "SelfCycleInTypeClassDeclaration");
check_failing_build_unit!(f_SelfImport, "SelfImport");
check_failing_build_unit!(f_SkolemEscape, "SkolemEscape");
check_failing_build_unit!(f_SkolemEscape2, "SkolemEscape2");
check_failing_build_unit_ignored!(f_SkolemEscapeKinds, "SkolemEscapeKinds", "expected: EscapedSkolem");
check_failing_build_unit_ignored!(f_StandaloneKindSignatures1, "StandaloneKindSignatures1", "expected: KindsDoNotUnify");
check_failing_build_unit_ignored!(f_StandaloneKindSignatures2, "StandaloneKindSignatures2", "expected: KindsDoNotUnify");
check_failing_build_unit_ignored!(f_StandaloneKindSignatures3, "StandaloneKindSignatures3", "expected: KindsDoNotUnify");
check_failing_build_unit_ignored!(f_StandaloneKindSignatures4, "StandaloneKindSignatures4", "expected: KindsDoNotUnify");
check_failing_build_unit!(f_SuggestComposition, "SuggestComposition");
check_failing_build_unit!(f_Superclasses1, "Superclasses1");
check_failing_build_unit!(f_Superclasses2, "Superclasses2");
check_failing_build_unit!(f_Superclasses3, "Superclasses3");
check_failing_build_unit!(f_Superclasses5, "Superclasses5");
check_failing_build_unit!(f_TooFewClassInstanceArgs, "TooFewClassInstanceArgs");
check_failing_build_unit!(f_TooFewUnnamedClassInstanceArgs, "TooFewUnnamedClassInstanceArgs");
check_failing_build_unit!(f_TopLevelCaseNoArgs, "TopLevelCaseNoArgs");
check_failing_build_unit!(f_TransitiveDctorExport, "TransitiveDctorExport");
check_failing_build_unit!(f_TransitiveDctorExportError, "TransitiveDctorExportError");
check_failing_build_unit!(f_TransitiveKindExport, "TransitiveKindExport");
check_failing_build_unit!(f_TransitiveSynonymExport, "TransitiveSynonymExport");
check_failing_build_unit!(f_TypeClasses2, "TypeClasses2");
check_failing_build_unit!(f_TypeError, "TypeError");
check_failing_build_unit!(f_TypeOperatorAliasNoExport, "TypeOperatorAliasNoExport");
check_failing_build_unit!(f_TypeSynonymCycle, "TypeSynonymCycle");
check_failing_build_unit!(f_TypeSynonyms, "TypeSynonyms");
check_failing_build_unit_ignored!(f_TypeSynonyms10, "TypeSynonyms10", "expected: KindsDoNotUnify");
check_failing_build_unit!(f_TypeSynonyms4, "TypeSynonyms4");
check_failing_build_unit!(f_TypeSynonyms5, "TypeSynonyms5");
check_failing_build_unit_ignored!(f_TypeSynonyms7, "TypeSynonyms7", "expected: InvalidInstanceHead");
check_failing_build_unit!(f_TypeSynonyms8, "TypeSynonyms8");
check_failing_build_unit!(f_TypeSynonyms9, "TypeSynonyms9");
check_failing_build_unit_ignored!(f_TypeSynonymsOverlappingInstance, "TypeSynonymsOverlappingInstance", "expected: OverlappingInstances");
check_failing_build_unit_ignored!(f_TypeSynonymsOverlappingUnnamedInstance, "TypeSynonymsOverlappingUnnamedInstance", "expected: OverlappingInstances");
check_failing_build_unit!(f_TypeWildcards1, "TypeWildcards1");
check_failing_build_unit!(f_TypeWildcards2, "TypeWildcards2");
check_failing_build_unit!(f_TypeWildcards3, "TypeWildcards3");
check_failing_build_unit!(f_TypeWildcards4, "TypeWildcards4");
check_failing_build_unit!(f_TypedBinders, "TypedBinders");
check_failing_build_unit!(f_TypedBinders2, "TypedBinders2");
check_failing_build_unit!(f_TypedBinders3, "TypedBinders3");
check_failing_build_unit!(f_TypedHole, "TypedHole");
check_failing_build_unit!(f_TypedHole2, "TypedHole2");
check_failing_build_unit!(f_TypedHole3, "TypedHole3");
check_failing_build_unit!(f_TypedHole4, "TypedHole4");
check_failing_build_unit_ignored!(f_UnderscoreModuleName, "UnderscoreModuleName", "expected: ErrorParsingModule");
check_failing_build_unit_ignored!(f_UnknownType, "UnknownType", "expected: UnknownName");
check_failing_build_unit_ignored!(f_UnsupportedFFICommonJSExports1, "UnsupportedFFICommonJSExports1", "expected: UnsupportedFFICommonJSExports");
check_failing_build_unit_ignored!(f_UnsupportedFFICommonJSExports2, "UnsupportedFFICommonJSExports2", "expected: UnsupportedFFICommonJSExports");
check_failing_build_unit_ignored!(f_UnsupportedFFICommonJSImports1, "UnsupportedFFICommonJSImports1", "expected: UnsupportedFFICommonJSImports");
check_failing_build_unit_ignored!(f_UnsupportedFFICommonJSImports2, "UnsupportedFFICommonJSImports2", "expected: UnsupportedFFICommonJSImports");
check_failing_build_unit!(f_UnsupportedRoleDeclarationTypeClass, "UnsupportedRoleDeclarationTypeClass");
check_failing_build_unit!(f_UnsupportedRoleDeclarationTypeSynonym, "UnsupportedRoleDeclarationTypeSynonym");
check_failing_build_unit_ignored!(f_UnsupportedTypeInKind, "UnsupportedTypeInKind", "expected: UnsupportedTypeInKind");
check_failing_build_unit_ignored!(f_VisibleTypeApplications1, "VisibleTypeApplications1", "expected: CannotApplyExpressionOfTypeOnType");
check_failing_build_unit_ignored!(f_VisibleTypeApplications2, "VisibleTypeApplications2", "expected: CannotApplyExpressionOfTypeOnType");
check_failing_build_unit_ignored!(f_WhereBindingChainAmbiguity, "WhereBindingChainAmbiguity", "expected: NoInstanceFound");
