// Generated by purs version 0.15.15
var myOrdInt = {
    myCompare: function (v) {
        return function (v1) {
            return 0;
        };
    },
    myLte: function (v) {
        return function (v1) {
            return true;
        };
    }
};
var myLte = function (dict) {
    return dict.myLte;
};
var myEqString = {
    myEq: function (v) {
        return function (v1) {
            return true;
        };
    }
};
var myEqInt = {
    myEq: function (v) {
        return function (v1) {
            return true;
        };
    }
};
var myEq = function (dict) {
    return dict.myEq;
};
var myCompare = function (dict) {
    return dict.myCompare;
};
var isEqual = function (dictMyEq) {
    var myEq1 = myEq(dictMyEq);
    return function (x) {
        return function (y) {
            return myEq1(x)(y);
        };
    };
};
var compareValues = function (dictMyOrd) {
    var myCompare1 = myCompare(dictMyOrd);
    return function (x) {
        return function (y) {
            return myCompare1(x)(y);
        };
    };
};
export {
    myCompare,
    myEq,
    myLte,
    isEqual,
    compareValues,
    myEqInt,
    myEqString,
    myOrdInt
};
