// Generated by purs version 0.15.15
import * as MyClass from "../MyClass/index.js";
var showThing = function (dictMyShow) {
    var myShow = MyClass.myShow(dictMyShow);
    return function (x) {
        return myShow(x);
    };
};
var showInt = /* #__PURE__ */ MyClass.myShow(MyClass.myShowInt)(42);
export {
    showThing,
    showInt
};
